### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by giacomobartoli** [IBM/alexa-skill-watson-assistant#55]
I've followed your guide and I am using the system without the Redis database.
Then, my .params consists of:
{
  "ASSISTANT_IAM_APIKEY": "__",
  "ASSISTANT_IAM_URL": "__",
  "WORKSPACE_ID": "__",
  "WEATHER_URL": "__"
}

I've double checked all those parameters and they're okay. However, when I am calling the Watson Assistant skill by typing "Ask weather channel what do you know about me" it returns "There was a problem with the requested skill's response". If try the same in the Watson Assistant try out, everything works fine. The endpoint to IBM Cloud Action is correctly inserted into the Amazon Developer Console.
By inspecting the log from the IBM Cloud Functions, this is what I get:

"logs": [
        "2019-08-20T20:00:52.308924Z    stdout: Begin action",
        "2019-08-20T20:00:52.308940Z    stdout: Alexa attributes:",
        "2019-08-20T20:00:52.308944Z    stdout: undefined",
        "2019-08-20T20:00:52.313028Z    **stdout: Connected to Watson Assistant"**,
        "2019-08-20T20:00:52.313038Z    stdout: Missing REDIS_URI Will use session attributes instead of Redis.",
        "2019-08-20T20:00:52.313042Z    stdout: Alexa sessionId: amzn1.echo-api.session.96d29f76-16a7-42fb-969f-2a56c365446f",
        "2019-08-20T20:00:52.313045Z    stdout: WORKSPACE_ID: c9d171f0-fef7-4a06-b338-0cab3d62b023",
        "2019-08-20T20:00:52.313047Z    stdout: Input text: start skill",
        "2019-08-20T20:00:53.407930Z    **stderr: { Not Found: Resource not found**",
        "2019-08-20T20:00:53.407971Z    stderr: at RequestWrapper.formatError (/nodejsAction/6mYD7bOa/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)",
        "2019-08-20T20:00:53.407975Z    stderr: at /nodejsAction/6mYD7bOa/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29",
        "2019-08-20T20:00:53.407978Z    stderr: at <anonymous>",
        "2019-08-20T20:00:53.407980Z    stderr: at process._tickCallback (internal/process/next_tick.js:189:7)",
        "2019-08-20T20:00:53.407983Z    stderr: name: 'Not Found',",
        "2019-08-20T20:00:53.407986Z    stderr: code: 404,",
        "2019-08-20T20:00:53.407989Z    stderr: message: 'Resource not found',",
        "2019-08-20T20:00:53.407991Z    stderr: body: '{\"error\":\"Resource not found\",\"code\":404}',",
        "2019-08-20T20:00:53.407994Z    stderr: headers:",
        "2019-08-20T20:00:53.407997Z    stderr: { 'content-type': 'application/json; charset=utf-8',",
        "2019-08-20T20:00:53.408000Z    stderr: 'content-length': '41',",
        "2019-08-20T20:00:53.408003Z    stderr: 'access-control-allow-origin': '*',",
        "2019-08-20T20:00:53.408005Z    stderr: 'access-control-allow-methods': 'GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS',",
        "2019-08-20T20:00:53.408008Z    stderr: 'access-control-allow-headers': 'Content-Type, Content-Length, Authorization, X-Watson-Authorization-Token, X-WDC-PL-OPT-OUT, X-Watson-UserInfo, X-Watson-Learning-Opt-Out, X-Watson-Metadata',",
        "2019-08-20T20:00:53.408011Z    stderr: 'access-control-max-age': '3600',",
        "2019-08-20T20:00:53.408014Z    stderr: 'content-security-policy': 'default-src \\'none\\'',",
        "2019-08-20T20:00:53.408016Z    stderr: 'x-dns-prefetch-control': 'off',",
        "2019-08-20T20:00:53.408019Z    stderr: 'x-frame-options': 'SAMEORIGIN',",
        "2019-08-20T20:00:53.408021Z    stderr: 'strict-transport-security': 'max-age=15552000; includeSubDomains',",
        "2019-08-20T20:00:53.408037Z    stderr: 'x-download-options': 'noopen',",
        "2019-08-20T20:00:53.408040Z    stderr: 'x-content-type-options': 'nosniff',",
        "2019-08-20T20:00:53.408042Z    stderr: 'x-xss-protection': '1; mode=block',",
        "2019-08-20T20:00:53.408045Z    stderr: 'x-global-transaction-id': '134256d06524db272f02ad85861aa9f2',",
        "2019-08-20T20:00:53.408048Z    stderr: 'x-dp-watson-tran-id': '134256d06524db272f02ad85861aa9f2',",
        "2019-08-20T20:00:53.408050Z    stderr: 'x-edgeconnect-midmile-rtt': '88',",
        "2019-08-20T20:00:53.408053Z    stderr: 'x-edgeconnect-origin-mex-latency': '112',",
        "2019-08-20T20:00:53.408056Z    stderr: date: 'Tue, 20 Aug 2019 20:00:53 GMT',",
        "2019-08-20T20:00:53.408058Z    stderr: connection: 'close' } }",
        "2019-08-20T20:00:53.408061Z    stderr: Caught error:",
        "2019-08-20T20:00:53.408082Z    stdout: Error: Error talking to Watson.",

PS: I've already seen issue #39 which seems related to mine.

**Comment by markstur** [comment]
It does look the same as the other issue. Never heard back on that one. It is trying to call assistant.message and getting a 404.  This usually means the URL is wrong (I guess it could also be a temporary failure, so retry of course).  The wrong URL would come from your .params  ASSISTANT_IAM_URL and possibly WORKSPACE_ID. Your workspace looks ok in the log, so just make sure skill is still there with the matching ID. I know you double-checked but not sure what else to suggest. Maybe you didn't use a full URL or something. It should look like this:

{
  "ASSISTANT_IAM_APIKEY": "aKK7imqIVSqeOAcT_x-0sCPAjHtmzg7xznABC-Z2a9Hi",
  "ASSISTANT_IAM_URL": "https://gateway.watsonplatform.net/assistant/api",
  "WORKSPACE_ID": "26a00ca0-c4b3-4e9b-b4e9-fcc7ab9e0045",
... and so on

I don't know if the APIKEY can result in a 404 (vs forbidden) but maybe. My guess is one of the other 2 are wrong (or temporarily not available).  Also make sure you aren't getting confused by updating one function but using a different one.

**Comment by giacomobartoli** [comment]
@markstur thank you for the support. Yes, you were right I was using the full url URL for the ASSISTANT_IAM_URL. That was my mistake, but I wasn't clear to me from the README. Anyway, thank you again you can close this issue.

**Comment by monicaInnovati** [comment]
Hello,
I have the same problem and still cannot manage it.
I followed the guide as is, the only thing different so far is to put the URL as this message was and add the parameter "WORKSPACE_ID", What else should I modify?, Thanks :)
